from selenium import webdriver
mail=input("Enter mail:")
passw=input("Enter password:")
b=webdriver.Chrome("C:\\Users\\VISERION\\Downloads\\chromedriver_win32\\chromedriver.exe")
b.get("https://www.linkedin.com/")
email=b.find_element_by_id("session_key")
email.send_keys(mail)
password=b.find_element_by_id("session_password")
password.send_keys(passw)
login=b.find_element_by_class_name("sign-in-form__submit-button")
login.click()
